### ISSUE TITLE
Provide own/custom logger object

### ISSUE THREAD

**Issue by diman82** [sighalt/logdecorator#12]
I've my own configuration of logger, that writes to FileHandler & StreamHandler, has custom formatting and etc..

I would like to use it.

How this is achievable with this library?

**Comment by sighalt** [comment]
Logdecorator does not mess with your logging configuration. At most it will instantiate a Logger object, which you can prevent by providing a `logger` keyword argument.

**Comment by sighalt** [comment]
@diman82 did this answer your question?

**Comment by diman82** [comment]
@sighalt According to documentation, you need to set logging level in each decorator, i.e. @log_on_error(logging.ERROR, "some message").
As I'm using a custom logger, I would expect to pass solely a logger object, something like:
@log_on_error(mycustomlogger, "some message"), and the logging level would be extracted from the logger object.
Is this supported?

**Comment by sighalt** [comment]
@diman82 This is not how Logger objects work. If you log a message using a Logger, you have to provide a log level. The log level set by `Logger.setLevel()` (which I think you are refering to) acts like a filter<sup>1</sup> not as a default.

<sup>1</sup> https://docs.python.org/3/library/logging.html#logging.Logger.setLevel

**Comment by diman82** [comment]
@sighalt You're right in describing how I set the logger, e.g.:
self.logger =logging.getLogger('mycustomlogger')
self.logger.setLevel(logging.INFO)
And then I can use my logger object to create log messages.

Setting/using .setLevel() makes the paradigm of passing the log level to each log function call redundant.

So, it would be nice to pass the logger object as decorator param, and reuse the logging level initially set in global config, instead of passing it with each decorator.

**Comment by sighalt** [comment]
@diman82 I think `setLevel()` does not, what you think it does. Setting a level on a logger object sets **only a threshold**. It is **not** supposed to define a default log level. So no redundancy here.

How would you log a message without defining a log level in plain python?
```
import logging

logger = logging.getLogger("mycustomlogger")
logger.setLevel(logging.INFO)

# <- insert logging here
```

It is to my understanding, that you can only use one of the following methods, which again, requires you to define a level:
```
# implicit definition of log level
logger.debug("...")
logger.info("...")
logger.warning("...")
logger.error("...")
logger.fatal("...")

# explicit definition of log level
logger.log(logging.DEBUG, "...")

**Comment by diman82** [comment]
@sighalt Thanks for the detailed explanation, it totally makes sense now!

Just a quick elaborative question before we close this:
Can the @log_on_error decorator accept any other log level than logging.ERROR, e.g.
@log_on_error(logging.INFO, 'some message')?
Also, what is thr difference between @log_on_error & log_exception decorators?

**Comment by sighalt** [comment]
@diman82 

> Can the @log_on_error decorator accept any other log level than logging.ERROR, e.g.
> @log_on_error(logging.INFO, 'some message')?

Yes, `log_on_error` refers to, that it is only invoked if an exception occurs. You can still set whatever log level you think is appropriate.

> Also, what is thr difference between @log_on_error & log_exception decorators?

`log_on_error` logs an arbitrary message of your choice with any given log level if an exception is raised, while `log_exception` logs your message **and** a stack trace to the ERROR level. (See [Logger.exception](https://docs.python.org/3/library/logging.html#logging.Logger.exception) for more information.)

e.g.
```
>> from logdecorator import log_on_error, log_exception
>>> import logging
>>> logging.basicConfig(level=logging.INFO)
>>> 
>>> @log_on_error(logging.INFO, "Just another error. Ignoring...", on_exceptions=ZeroDivisionError, reraise=False)
... def my_faulty_function():
...     return 10 / 0
... 
>>>
>>> my_faulty_function()
INFO:__main__:Just another error. Ignoring...
>>>
>>> @log_exception("Darn method raises error again:", on_exceptions=ZeroDivisionError, reraise=False)
... def my_faulty_function():
...     return 10 / 0
... 
>>> my_faulty_function()
ERROR:__main__:Darn method raises error again:
Traceback (most recent call last):
  File "/not_revealed_directory/logdecorator/decorator.py", line 107, in on_error
    raise exception
  File "/not_revealed_directory/logdecorator/decorator.py", line 101, in execute
    return super().execute(fn, *args, **kwargs)
  File "/not_revealed_directory/logdecorator/decorator.py", line 9, in execute
    return fn(*args, **kwargs)
  File "<stdin>", line 3, in my_faulty_function
ZeroDivisionError: division by zero

**Comment by diman82** [comment]
@sighalt Thanks for detailed explanation and great collaboration!

**Comment by sighalt** [comment]
@diman82 You're welcome :+1:
