### ISSUE TITLE
Using data accessible via 'self' in messages for decorated methods

### ISSUE THREAD

**Issue by mazz3rr** [sighalt/logdecorator#17]
It would be nice to be able to have access in messages to data sitting on `self`, if the decorated function is a method.

For instance, I use `logdecorator` with my `SshClient` class (a simple wrapper for some features of `paramiko` and `scp`). So I use `log_on_start` on my `connect()` method and the message is a simple:

 `"Establishing connection"`. 

But if I had access to `host` and `port` that are sitting unused on `self`, the message would be a more descriptive: 

`"Establishing connection to {host}:{port}"`.

**Comment by sighalt** [comment]
@z33kz33k you can use self as follows:

"Establishing connection to {self.host}:{self.port}".

**Comment by mazz3rr** [comment]
Thanks. It indeed works as described. So this issue can be closed as already implemented.
