### ISSUE TITLE
Please consider typing this useful package

### ISSUE THREAD

**Issue by linearcombination** [sighalt/logdecorator#18]
Starting to use mypy --strict which disallows usage of this decorator package since it is untyped. If I had more time I'd fork it and type it for you. So, it is just a wishlist item for those of us whose projects need or want to pass mypy --strict type checking. Great package, thanks!

This would be a useful resource if you decide to undertake this: [Typing decorators](https://dev.to/tusharsadhwani/the-comprehensive-guide-to-mypy-561m#typing-decorators)

**Comment by sighalt** [comment]
Good idea, I will have a look at it.

**Comment by sighalt** [comment]
Implemented and uploaded to PyPI. This feature is available from version 2.4.
