### ISSUE TITLE
log_on_error and log_exception should reraise by default

### ISSUE THREAD

**Issue by Skazu** [sighalt/logdecorator#2]
Hi and thanks for this awesome project,
i think you should consider making `log_on_error` and `log_exception` decorators reraise exceptions by default.
Otherwise adding those decorators would change my existing program flow (of course i can explicit set `reraise` to `true`, but in my opinion the logging part should not per default affect the flow of my program).

**Comment by sighalt** [comment]
I fully agree to your suggestion. Since this is a breaking change, I'll soon introduce a deprecation warning when someone is relying on the current default behaviour.

I leave this issue as open until the default parameter has changed in some future release.

**Comment by sighalt** [comment]
I pushed version 2.1 to pypi, which introduces the announced deprecation warning.

**Comment by sighalt** [comment]
This change will be available in logdecorator 2.2 and is already implemented in the release branch #7

**Comment by sighalt** [comment]
PR was merged into master branch.
