### ISSUE TITLE
Log on specific result

### ISSUE THREAD

**Issue by Skazu** [sighalt/logdecorator#3]
Hi,
we want to add some log messages if a method returns a specific result (like `False` or `None`). I couldn't find a suitable decorator to archive this behaviour.

Are there any plans to add a decorator like described above to your project?

Or maybe you can explain how to extend your code to write my own decorator, based on your code?

**Comment by sighalt** [comment]
Since this is kind of a special case I suggest to create a custom decorator, based on `log_on_end`.

```python
from logdecorator import log_on_end

class log_on_result(log_on_end):
    def __init__(self, *args, **kwargs):
        self.specific_result = kwargs.pop("specific_result")
        super().__init__(*args, **kwargs)

    def after_execution(self, fn, result, *args, **kwargs):
        if result == self.specific_result or result is self.specific_result:
            super().after_execution(fn, result, *args, **kwargs)

```
