### ISSUE TITLE
TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by Skazu** [sighalt/logdecorator#4]
Hi,

there seems to be a mistake in your documentation, if i try to log errors like this:
```
@log_on_error(logging.ERROR, "Error on downloading",
              on_exceptions=[MyException1, MyException2],
              reraise=True)
```

i receive the following error:
`TypeError: catching classes that do not inherit from BaseException is not allowed`

this is because you try to catch the exceptions like defined in `on_exceptions` but the Python Docs (*) state the following:

> An except clause may name multiple exceptions as a parenthesized **tuple**, for example:

so we must use the decorator like this:
```
@log_on_error(logging.ERROR, "Error on downloading",
              on_exceptions=(MyException1, MyException2),
              reraise=True)
```

* https://docs.python.org/3/tutorial/errors.html#handling-exceptions

**Comment by sighalt** [comment]
Thank you for pointing this out. I changed the docs accordingly.

**Comment by Shahbaz894** [comment]
i found this error.
TypeError: catching classes that do not inherit from BaseException is not allowed

   try:
                con=pymysql.connect(host="localhost", user="root", password="", database="employee")
                cur=con.cursor()
                cur.execute("select* from registration where email=%s",self.text_email.get())
                row=cur.fetchone()
                print(row)
                if row!=None:


                    messagebox.showError("Error", "User already exist", parent=self.root)

                else:
                    cur.execute("insert into registration(fname,lname,contact,email,question,answer,password) values (%s,%s,%s,%s,%s,%s,%s) ",
                                (self.var_fname.get(),
                                 self.text_lname.get(),
                                 self.text_contact.get(),
                                 self.text_email.get(),
                                 self.cmb_quest.get(),
                                 self.text_answer.get(),
                                 self.text_password.get()

                                ))
                    con.commit()
                    con.close()

                messagebox.showinfo("Success", "Data enter successfuly", parent=self.root)
            except EXCEPTION as es:

                messagebox.showinfo("Error", f"Error due to:{str(es)}", parent=self.root)
