### ISSUE TITLE
Decorator access local variable inside a function

### ISSUE THREAD

**Issue by ninn55** [sighalt/logdecorator#8]
Is it possiable to access local variable inside a function with log decorator ?

**Comment by sighalt** [comment]
Unfortunatelly not. It's only possible to access the given parameters, the return value and/or the raised exception. Also, I don't see how it might be possible to access local variables, without a considerable amount of hacking.

If you are in the need of logging something inside a function, the function is probably doing more than only one thing and it would be best to split it into multiple functions. This might then lead to the possibility to use the capabilities of logdecorator again.
